name: video_codec_plugin
description: A Flutter plugin to detect video codec from local files on iOS.
version: 0.0.1
homepage: https://github.com/heshanka/video_codec_plugin
repository: https://github.com/heshanka/video_codec_plugin

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: VideoCodecPlugin

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  plugin_platform_interface: ^2.1.4